### ISSUE TITLE
Feature: User can view the Pokemon

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all of the Pokemon in the first generation

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

All of the Pokemon will be visible and the user will scroll up and down to view more available Pokemon

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/192325877-50769b40-c589-4b87-bc62-81f966d14272.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header bar with naming the page listed
- [x] Create one card and ensure styling and design is displayed in the formation desired
- [x] Create container / layout classes to be used for formatting the the page / visible Pokemon
- [x] Create a function to make the card and use the styling in place
- [x] Pull the necessary data from the API to have the Pokemon name and number
- [x] Create a loop to display all of the Pokemon images, number, and name
- [x] Check that created cards look uniform to the test card
- [x] Remove the test card
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
