### ISSUE TITLE
Feature: User can click on a Pokemon to view more information

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a Pokemon card to view more information on the Pokemon 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click on a Pokemon card will display a new view of only the Pokemon, their description, stats, and evolutions

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/192327190-ebd3abe7-bb36-4e38-bd5d-168c92659567.png)

![image](https://user-images.githubusercontent.com/109567499/192327269-05f2b65e-8b1a-4355-ab32-b4917f0b23e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Hide previously created header and Pokemon list
- [x] Create the view for details page using hard coding for the display information to see the layout
- [x] Add CSS to make the look uniform on desktop view like the wireframes
- [x] Hide the detailed display and show the Pokemon list
- [x] Listen for clicks on list of Pokemon cards
  - [x] Possibly add the pokemon ID number as the div ID when creating the cards
- [x] When the card is clicked show the detailed display
- [x] Create an icon to close the detailed display
- [x] Listen for clicks on the icon 
  - [x] If the icon is clicked, hide the detailed display and show the Pokemon list
- [x] Adjust the listener function on the cards to take the id number from the card
  - [x] Use the ID number to:
    - [x] Make a detailed request from the API and get the height, weight, type, ability, stats
      - [x] Create functions to calculate the height and weight into ft/in and lbs and use to create a string to display
      - [x] Capitalize abilities and display
      - [x] Create css classes for each type background color
        - [x] Use the first type for the primary background color used
      - [x] Create function to check stat name display and adjust for capitalization
        - [x] Use type color for bar display
    - [x] Make a detailed request from the API and get the flavor text and evolution chain
      - [x] Run through the evolution chain and get the evolution line names
        - [x] Iterate through the names and through the array of  Pokemon used in feature 1
          - [x] Match pokemon name (check for case sensitivity if needed) and take ID number
            - [x] Use ID number to match with png image to display
            - [x] Display image and name
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
