### ISSUE TITLE
Feature: User can view Pokemon in different generations

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#26]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view additional Pokemon in different generations.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on a region name in the header to change the view and see the Pokemon in that generation

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/194166468-4855ca9e-ae54-476a-af55-65fba1d6dc94.png)

![image](https://user-images.githubusercontent.com/109567499/194166512-7b56ef3e-e0e0-493d-a54f-a6710112c4af.png)

![image](https://user-images.githubusercontent.com/109567499/194166562-a928a0b2-d145-4e77-acac-1bde859545f6.png)

![image](https://user-images.githubusercontent.com/109567499/194166588-aaefe535-b298-41da-8f80-77e739cf415c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make visual changes to header
  - [x] Remove Kanto name from title
  - [x] Move search bar to below the header box
    - [x] Change search border color and magnifying glass color
  - [x] Create a div to hold the group of regions
    - [x] Make the div a flex container
    - [x] Make a div for each region (maybe column-eighth?)
    - [x] Name each region inside of an anchor tag
- [x] Create another div for view for second generation
- [x] Change card loading XML request to pull all pokemon instead of first generation.
- [x] Add assets and rename to hold all images of Pokemon original artwork
  - [x] Make sure to correct any links to images to find the correct folder
- [x] Have Pokemon whose entry_id is < 152 appended to "Kanto" view, any Pokemon whose entry_id is < 252 appened to "Johto" view (new div created). and end the loop at 253 for the time being.
  - [x] Check first that the new Pokemon are below the current generation
    - [x] Test by targeting the first generation and adding class hidden to see if only new generation shows
- [x] Listen to clicks on the anchor elements
  - [x] Create a function that checks for the data-view property
    - [x] Hide each view
      - [x] If data-view matches it should show that region's Pokemon
- [x] Check to make sure detailed view display works with new regions
  - [x] If not, adjust function target or target new generation with the same function
- [x] Once everything is working correctly, repeat for future generations
- [x] Scroll to check that Pokemon are in correct regions
- [x] Test random Pokemon across all generations to ensure all functions are working property
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
