### ISSUE TITLE
Feature: User can click evolutions to move pages

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#27]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on evolution in detailed view to go to evolution's detailed view page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the evolution part of the detailed view and be moved to the Pokemon they clicked on's detailed page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/194168864-9c68c12e-1284-4e8c-a866-1d6c63c00038.png)

![image](https://user-images.githubusercontent.com/109567499/194168895-2e2ebbd5-296c-4bb1-a22b-87f0cdc12fca.png)

![image](https://user-images.githubusercontent.com/109567499/194168932-72374f8c-57ec-4895-919d-0f9f8523da7c.png)

![image](https://user-images.githubusercontent.com/109567499/194168960-c548ffbd-da5b-4b02-b0f5-51a5c292ed04.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a class to the container of evolution elements
- [x] Create a variable that queries the DOM for the evolutions container
- [x] In the function that renders the evolutions, set the evo-div id property as the value of the evolution name
- [x] xmark should clear the id value when resetting
- [x] Listen for clicks on the evolution container
  - [x] If the event.target.closest  evolution div is null, end the function
- [x] Run the id value (name of evolution) through national dex and match with the species name
  - [x] If they match use that object to go into the detailed View
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
