### ISSUE TITLE
Feature: User can favourite a Pokemon

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favourite a Pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A heart icon will be displayed on the detailed Pokemon screen that can be clicked to set the Pokemon as a favourite

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/192327586-dc239020-98c4-41ec-9805-afe2df40d73c.png)

![image](https://user-images.githubusercontent.com/109567499/192327698-bf1ad5f0-ce10-4f50-8207-396dc02f4680.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a heart icon to the detailed view of the Pokemon
- [x] Listen for clicks on the heart icon
  - [x] When clicked:
    - [x] Color should change from white to red
    - [x] Should add a favourited tag to the image
- [x] Set up local storage
  - [x] Save a copy of the Pokemon array to local storage
  - [x] If a pokemon is favourited then a favourited tag should be set to the local storage with a value of true
- [x] When the page is reloaded the Pokemon should:
  - [x] Have a favourited tag if favourited before refresh
  - [x] Display the favourited red display for the heart icon if the detailed screen is reopened
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
