### ISSUE TITLE
Feature: User can view their favourite Pokemon

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a similar icon on the entire Pokedex page to view their favourite Pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Favouriting a Pokemon will add a class to the Pokemon. When the icon is click it will only display the Pokemon with the favourited class.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/192328088-e2eac2f1-d38e-4a24-a215-b8ce14b2b813.png)

![image](https://user-images.githubusercontent.com/109567499/192328180-c8f9df4d-e4b3-4914-86b9-886be2700878.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a heart icon to the title bar
- [x] Create a new view for the favourite Pokemon
- [x] Listen for clicks on the heart icon
  - [x] if on main display:
    - [x] Sort the array of favourited Pokemon by entry_id number
    - [x] Create new cards for all of the favourited Pokemon
      - [x] Make sure function to create cards can be reused here
      - [x] Make sure function for detailed display works here
    - [x] hide the view of all cards
  - [x] if on fav display:
    - [x] hide fav Pokemon view
    - [x] display all card view
- [x] Add data-view properties to the main display and fav display (and a property to the data model)
- [x] Save the most recent view to local storage
- [x] Use local storage of recent view to check what last page was and load that page
- [x] Use local storage to know when closing detailed view which view to go to (main or fav)
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
