### ISSUE TITLE
Feature: User can search for a Pokemon

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type a Pokemon name or number into a search bar to view the Pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As a user is typing the name or number the page will start to display Pokemon whose name or numbers include what is being typed (starts to hide Pokemon that do not have any matching information [filtering out Pokemon])

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/192328499-a86f36e7-b938-43d6-91b6-4b23e808b827.png)

![image](https://user-images.githubusercontent.com/109567499/192328567-6a169810-66b9-42b1-b719-a361aa6dcead.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a search bar and a magnifying glass icon
  - [x] Magnifying glass should put focus on search bar or enter search bar
- [x] Listen for inputs in the search bar
  - [x] Select all pokemon cards that are in that view (main or fav)
  - [x] Search through the pokemon cards name text and number text
  - [x] If the text content includes the search text, show the cards
    - [x] Search should be case sensitive
    - [x] Make sure the search does not show fav pokemon on main screen and vice versa
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
